In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [23]:
df = pd.read_csv(r"C:\Users\kunwa\PycharmProjects\ML\Practice_1 1-49\house-prices-advanced-regression-techniques\train.csv")
from sklearn.model_selection import train_test_split

X = df.drop(columns=["SalePrice"])
y = np.log1p(df["SalePrice"])

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [25]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [26]:
x_train["Alley"] = x_train["Alley"].fillna("No Alley")
x_test["Alley"] = x_test["Alley"].fillna("No Alley")

In [27]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [28]:
x_train["LotFrontage"] = (
    x_train.groupby("Neighborhood")["LotFrontage"]
           .transform(lambda x: x.fillna(x.median()))
)
x_test["LotFrontage"] = (
    x_test.groupby("Neighborhood")["LotFrontage"]
           .transform(lambda x: x.fillna(x.median()))
)

C:\Users\kunwa\PycharmProjects\ML\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [29]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [30]:
x_train["Fence"] = x_train["Fence"].fillna("No Fence")
x_test["Fence"] = x_test["Fence"].fillna("No Fence")
x_train["MiscFeature"] = x_train["MiscFeature"].fillna("None")
x_test["MiscFeature"] = x_test["MiscFeature"].fillna("None")
x_train["PoolQC"] = x_train["PoolQC"].fillna("No Pool")
x_test["PoolQC"] = x_test["PoolQC"].fillna("No Pool")
x_train["MasVnrType"] = x_train["MasVnrType"].fillna("None")
x_test["MasVnrType"] = x_test["MasVnrType"].fillna("None")
x_train["FireplaceQu"] = x_train["FireplaceQu"].fillna("No Fireplace")
x_test["FireplaceQu"] = x_test["FireplaceQu"].fillna("No Fireplace")
x_train["GarageYrBlt"] = x_train["GarageYrBlt"].fillna(0.0)
x_test["GarageYrBlt"] = x_test["GarageYrBlt"].fillna(0.0)

garage_cat_cols = [
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
]

bsmt_cat_cols = [
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2"
]

x_train[garage_cat_cols] = x_train[garage_cat_cols].fillna("No Garage")
x_test[garage_cat_cols] = x_test[garage_cat_cols].fillna("No Garage")
x_train[bsmt_cat_cols] = x_train[bsmt_cat_cols].fillna("No Basement")
x_test[bsmt_cat_cols] = x_test[bsmt_cat_cols].fillna("No Basement")
x_train['MasVnrArea'] = x_train["MasVnrArea"].fillna(0.0)
x_test['MasVnrArea'] = x_test["MasVnrArea"].fillna(0.0)

In [31]:
x_train = x_train.drop(columns=["Id"])
x_test = x_test.drop(columns=["Id"])

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [33]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [34]:
num_df = df.select_dtypes(include=["int64", "float64"])

num_df

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [35]:
str_df = df.select_dtypes(include=["object"])
str_df

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [36]:
ordinal_cols = [
    "LotShape",
    "LandSlope",
    "ExterQual",
    "ExterCond",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "HeatingQC",
    "KitchenQual",
    "Functional",
    "FireplaceQu",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PavedDrive",
    "PoolQC",
    "Fence",
    "Alley"
]

categories = [
    ["IR3", "IR2", "IR1", "Reg"],                      # LotShape
    ["Sev", "Mod", "Gtl"],                             # LandSlope
    ["Po", "Fa", "TA", "Gd", "Ex"],                    # ExterQual
    ["Po", "Fa", "TA", "Gd", "Ex"],                    # ExterCond
    ["No Basement", "Po", "Fa", "TA", "Gd", "Ex"],     # BsmtQual
    ["No Basement", "Po", "Fa", "TA", "Gd", "Ex"],     # BsmtCond
    ["No Basement", "No", "Mn", "Av", "Gd"],           # BsmtExposure
    ["No Basement", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],  # BsmtFinType1
    ["No Basement", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],  # BsmtFinType2
    ["Po", "Fa", "TA", "Gd", "Ex"],                    # HeatingQC
    ["Po", "Fa", "TA", "Gd", "Ex"],                    # KitchenQual
    ["Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"],  # Functional
    ["No Fireplace", "Po", "Fa", "TA", "Gd", "Ex"],    # FireplaceQu
    ["No Garage", "Unf", "RFn", "Fin"],                # GarageFinish
    ["No Garage", "Po", "Fa", "TA", "Gd", "Ex"],       # GarageQual
    ["No Garage", "Po", "Fa", "TA", "Gd", "Ex"],       # GarageCond
    ["N", "P", "Y"],                                   # PavedDrive
    ["No Pool", "Fa", "TA", "Gd", "Ex"],               # PoolQC
    ["No Fence", "MnWw", "GdWo", "MnPrv", "GdPrv"],    # Fence
    ["No Alley", "Grvl", "Pave"]                       # Alley
]

In [37]:
onehot_cols = [
    "MSSubClass",
    "MSZoning",
    "LotConfig",
    "LandContour",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "Foundation",
    "Heating",
    "Electrical",
    "GarageType",
    "MiscFeature",
    "SaleType",
    "SaleCondition"
]

In [38]:
from sklearn.compose import ColumnTransformer
import category_encoders as ce
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ("tf1", ce.BinaryEncoder(), ["Street", "CentralAir"]),
        ("tf2", OrdinalEncoder(categories=categories), ordinal_cols),
        ("tf3", OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore"), onehot_cols)
    ],
    remainder="passthrough"
)

In [39]:
x_train["HouseAge"] = (
    x_train["YrSold"] - x_train["YearBuilt"]
)

x_test["HouseAge"] = (
    x_test["YrSold"] - x_test["YearBuilt"]
)

x_train["RemodelAge"] = (
    x_train["YrSold"] - x_train["YearRemodAdd"]
)

x_test["RemodelAge"] = (
    x_test["YrSold"] - x_test["YearRemodAdd"]
)

x_train["TotalBath"] = (
    x_train["FullBath"]
    + 0.5 * x_train["HalfBath"]
    + x_train["BsmtFullBath"]
    + 0.5 * x_train["BsmtHalfBath"]
)

x_test["TotalBath"] = (
    x_test["FullBath"]
    + 0.5 * x_test["HalfBath"]
    + x_test["BsmtFullBath"]
    + 0.5 * x_test["BsmtHalfBath"]
)

x_train["TotalPorchSF"] = (
    x_train["OpenPorchSF"]
    + x_train["EnclosedPorch"]
    + x_train["3SsnPorch"]
    + x_train["ScreenPorch"]
)

x_test["TotalPorchSF"] = (
    x_test["OpenPorchSF"]
    + x_test["EnclosedPorch"]
    + x_test["3SsnPorch"]
    + x_test["ScreenPorch"]
)

x_train["TotalSF"] = (
    x_train["TotalBsmtSF"] +
    x_train["1stFlrSF"] +
    x_train["2ndFlrSF"]
)

x_test["TotalSF"] = (
    x_test["TotalBsmtSF"] +
    x_test["1stFlrSF"] +
    x_test["2ndFlrSF"]
)

x_train["TotalBath"] = (
    x_train["FullBath"] +
    0.5 * x_train["HalfBath"] +
    x_train["BsmtFullBath"] +
    0.5 * x_train["BsmtHalfBath"]
)

x_test["TotalBath"] = (
    x_test["FullBath"] +
    0.5 * x_test["HalfBath"] +
    x_test["BsmtFullBath"] +
    0.5 * x_test["BsmtHalfBath"]
)

x_train["HouseAge"] = x_train["YrSold"] - x_train["YearBuilt"]

x_test["HouseAge"] = x_test["YrSold"] - x_test["YearBuilt"]

x_train["RemodelAge"] = x_train["YrSold"] - x_train["YearRemodAdd"]
x_test["RemodelAge"] = x_test["YrSold"] - x_test["YearRemodAdd"]

x_train["TotalPorchSF"] = (
    x_train["OpenPorchSF"] +
    x_train["EnclosedPorch"] +
    x_train["3SsnPorch"] +
    x_train["ScreenPorch"]
)

x_test["TotalPorchSF"] = (
    x_test["OpenPorchSF"] +
    x_test["EnclosedPorch"] +
    x_test["3SsnPorch"] +
    x_test["ScreenPorch"]
)

x_train["TotalHouseSF"] = (
    x_train["GrLivArea"] +
    x_train["TotalBsmtSF"]
)
x_test["TotalHouseSF"] = (
    x_test["GrLivArea"] +
    x_test["TotalBsmtSF"]
)

x_train["TotalOutdoorSF"] = (
    x_train["WoodDeckSF"] +
    x_train["OpenPorchSF"] +
    x_train["EnclosedPorch"] +
    x_train["3SsnPorch"] +
    x_train["ScreenPorch"]
)

x_test["TotalOutdoorSF"] = (
    x_test["WoodDeckSF"] +
    x_test["OpenPorchSF"] +
    x_test["EnclosedPorch"] +
    x_test["3SsnPorch"] +
    x_test["ScreenPorch"]
)

x_train["GarageScore"] = (
    x_train["GarageCars"] *
    x_train["GarageArea"]
)

x_test["GarageScore"] = (
    x_test["GarageCars"] *
    x_test["GarageArea"]
)

x_train["TotalRooms"] = (
    x_train["TotRmsAbvGrd"] +
    x_train["BedroomAbvGr"]
)

x_test["TotalRooms"] = (
    x_test["TotRmsAbvGrd"] +
    x_test["BedroomAbvGr"]
)

x_train["OverallScore"] = (
    x_train["OverallQual"] *
    x_train["OverallCond"]
)

x_test["OverallScore"] = (
    x_test["OverallQual"] *
    x_test["OverallCond"]
)

# Transform training data
train_transformed = transformer.fit_transform(x_train)

feature_names = transformer.get_feature_names_out()

new_train = pd.DataFrame(
    train_transformed,
    columns=feature_names,
    index=x_train.index
)

# Transform test data (DO NOT FIT AGAIN)
test_transformed = transformer.transform(x_test)

new_test = pd.DataFrame(
    test_transformed,
    columns=feature_names,
    index=x_test.index
)

C:\Users\kunwa\PycharmProjects\ML\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [10, 16] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [40]:
for df_temp in [new_train, new_test]:
    object_cols = df_temp.select_dtypes(include=["object"]).columns
    for col in object_cols:
        df_temp[col] = pd.to_numeric(df_temp[col], errors="coerce")

In [41]:
new_train = new_train.drop(columns=["remainder__Utilities"])
new_test = new_test.drop(columns=["remainder__Utilities"])

In [42]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import numpy as np

rf = RandomForestRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

scores = cross_val_score(
    rf,
    new_train,
    y_train,
    cv=5,
    scoring="r2"
)

print("R² Scores:", scores)
print("Average R²:", scores.mean())

rmse = np.sqrt(
    -cross_val_score(
        rf,
        new_train,
        y_train,
        cv=5,
        scoring="neg_mean_squared_error"
    )
)

print("Average RMSE:", rmse.mean())

R² Scores: [0.89889122 0.82418343 0.85298037 0.88386396 0.89707311]
Average R²: 0.8713984179501206
Average RMSE: 0.13894170287988653

In [43]:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV

xgb = XGBRegressor(
    random_state=42,
    objective="reg:squarederror"
)

param_dist = {
    "n_estimators": [300,500,700,1000,1500],
    "max_depth": [3,4,5,6,8,10],
    "learning_rate": [0.01,0.03,0.05,0.1],
    "subsample": [0.6,0.8,1.0],
    "colsample_bytree": [0.6,0.8,1.0],
    "min_child_weight": [1,3,5,7],
    "gamma": [0,0.1,0.3,0.5],
    "reg_alpha": [0,0.01,0.1,1],
    "reg_lambda": [0.5,1,2,5]
}

search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=100,
    cv=5,
    scoring="r2",
    random_state=42,
    n_jobs=-1,
    verbose=2
)

search.fit(new_train, y_train)

print("Best Score:", search.best_score_)
print("Best Parameters:")
print(search.best_params_)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
Best Score: 0.898064787848728
Best Parameters:
{'subsample': 1.0, 'reg_lambda': 0.5, 'reg_alpha': 0.01, 'n_estimators': 300, 'min_child_weight': 1, 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0, 'colsample_bytree': 0.6}

In [44]:
from sklearn.metrics import r2_score, root_mean_squared_error

best_model = search.best_estimator_

best_model.fit(new_train, y_train)

train_pred = np.expm1(best_model.predict(new_train))
test_pred = np.expm1(best_model.predict(new_test))

train_actual = np.expm1(y_train)
test_actual = np.expm1(y_test)

train_r2 = r2_score(train_actual, train_pred)
test_r2 = r2_score(test_actual, test_pred)

train_rmse = root_mean_squared_error(train_actual, train_pred)
test_rmse = root_mean_squared_error(test_actual, test_pred)

print("Training R² :", round(train_r2,4))
print("Testing R²  :", round(test_r2,4))
print()

print("Training RMSE :", round(train_rmse,4))
print("Testing RMSE  :", round(test_rmse,4))

Training R² : 0.9737
Testing R²  : 0.9008

Training RMSE : 12513.9366
Testing RMSE  : 27589.7627

In [45]:
importance = pd.Series(
    best_model.feature_importances_,
    index=new_train.columns
).sort_values(ascending=False)

print(importance.head(30))

remainder__TotalSF           0.155696
remainder__OverallQual       0.137922
tf2__KitchenQual             0.054427
remainder__GarageCars        0.046417
remainder__TotalBath         0.042322
remainder__OverallScore      0.040667
remainder__KitchenAbvGr      0.038021
remainder__TotalHouseSF      0.037499
tf2__GarageFinish            0.035612
tf2__GarageQual              0.031350
tf1__CentralAir_1            0.029426
tf2__FireplaceQu             0.024853
tf3__MSZoning_RM             0.024000
tf2__BsmtQual                0.017871
remainder__GarageScore       0.017539
tf2__GarageCond              0.015183
remainder__RemodelAge        0.014341
remainder__HouseAge          0.012706
remainder__YearBuilt         0.012703
remainder__GrLivArea         0.011762
tf3__MSZoning_RL             0.010899
tf1__CentralAir_0            0.009575
tf3__Neighborhood_Edwards    0.007527
remainder__BsmtFinSF1        0.007106
remainder__YearRemodAdd      0.007008
remainder__Fireplaces        0.006451
tf3__MSSubClass_30           0.006338
tf3__GarageType_Detchd       0.005585
tf3__MSSubClass_60           0.005559
remainder__LotArea           0.004494
dtype: float32

In [46]:
from catboost import CatBoostRegressor
from sklearn.metrics import r2_score, root_mean_squared_error
cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    loss_function="RMSE",
    random_seed=42,
    verbose=100
)

cat_model.fit(
    new_train,
    y_train
)

0:	learn: 0.3764544	total: 151ms	remaining: 2m 31s
100:	learn: 0.1052701	total: 762ms	remaining: 6.78s
200:	learn: 0.0835352	total: 1.25s	remaining: 4.98s
300:	learn: 0.0692247	total: 1.66s	remaining: 3.87s
400:	learn: 0.0585890	total: 2.09s	remaining: 3.12s
500:	learn: 0.0509594	total: 2.56s	remaining: 2.55s
600:	learn: 0.0443402	total: 3.02s	remaining: 2s
700:	learn: 0.0383530	total: 3.57s	remaining: 1.52s
800:	learn: 0.0335391	total: 3.96s	remaining: 983ms
900:	learn: 0.0299805	total: 4.35s	remaining: 478ms
999:	learn: 0.0264541	total: 4.86s	remaining: 0us

CatBoostRegressor(depth=6, iterations=1000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [47]:
train_pred = cat_model.predict(new_train)
test_pred = cat_model.predict(new_test)
train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, test_pred)

train_rmse = root_mean_squared_error(y_train, train_pred)
test_rmse = root_mean_squared_error(y_test, test_pred)

print(f"Training R² : {train_r2:.4f}")
print(f"Testing R²  : {test_r2:.4f}")

print()

print(f"Training RMSE : {train_rmse:.4f}")
print(f"Testing RMSE  : {test_rmse:.4f}")
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(
    cat_model,
    new_train,
    y_train,
    cv=5,
    scoring="r2"
)

print("R² Scores:", scores)
print("Average R²:", scores.mean())

rmse = np.sqrt(
    -cross_val_score(
        cat_model,
        new_train,
        y_train,
        cv=5,
        scoring="neg_mean_squared_error"
    )
)

print("Average RMSE:", rmse.mean())

Training R² : 0.9954
Testing R²  : 0.9042

Training RMSE : 0.0265
Testing RMSE  : 0.1337
0:	learn: 0.3783834	total: 7.71ms	remaining: 7.71s
100:	learn: 0.1052506	total: 718ms	remaining: 6.39s
200:	learn: 0.0805723	total: 1.23s	remaining: 4.88s
300:	learn: 0.0651217	total: 1.67s	remaining: 3.87s
400:	learn: 0.0549365	total: 2.1s	remaining: 3.14s
500:	learn: 0.0452304	total: 2.57s	remaining: 2.56s
600:	learn: 0.0390091	total: 3.02s	remaining: 2.01s
700:	learn: 0.0333101	total: 3.51s	remaining: 1.5s
800:	learn: 0.0284925	total: 4.06s	remaining: 1.01s
900:	learn: 0.0243937	total: 4.56s	remaining: 501ms
999:	learn: 0.0208649	total: 5.12s	remaining: 0us
0:	learn: 0.3794969	total: 7.92ms	remaining: 7.92s
100:	learn: 0.1018032	total: 585ms	remaining: 5.21s
200:	learn: 0.0800223	total: 980ms	remaining: 3.9s
300:	learn: 0.0665577	total: 1.39s	remaining: 3.23s
400:	learn: 0.0554048	total: 2.47s	remaining: 3.69s
500:	learn: 0.0459659	total: 3.04s	remaining: 3.02s
600:	learn: 0.0385716	total: 3.43s	remaining: 2.28s
700:	learn: 0.0331637	total: 3.87s	remaining: 1.65s
800:	learn: 0.0288285	total: 4.25s	remaining: 1.05s
900:	learn: 0.0250925	total: 4.75s	remaining: 523ms
999:	learn: 0.0217112	total: 5.39s	remaining: 0us
0:	learn: 0.3654771	total: 8.88ms	remaining: 8.87s
100:	learn: 0.1009831	total: 570ms	remaining: 5.07s
200:	learn: 0.0813126	total: 1.05s	remaining: 4.16s
300:	learn: 0.0672490	total: 1.45s	remaining: 3.36s
400:	learn: 0.0558627	total: 2.07s	remaining: 3.1s
500:	learn: 0.0462434	total: 2.6s	remaining: 2.59s
600:	learn: 0.0390710	total: 3.11s	remaining: 2.06s
700:	learn: 0.0329016	total: 3.71s	remaining: 1.58s
800:	learn: 0.0279519	total: 4.31s	remaining: 1.07s
900:	learn: 0.0240839	total: 4.75s	remaining: 521ms
999:	learn: 0.0210700	total: 5.15s	remaining: 0us
0:	learn: 0.3796258	total: 5.04ms	remaining: 5.04s
100:	learn: 0.1051636	total: 554ms	remaining: 4.93s
200:	learn: 0.0831720	total: 1.13s	remaining: 4.5s
300:	learn: 0.0679759	total: 1.57s	remaining: 3.65s
400:	learn: 0.0558960	total: 2.1s	remaining: 3.14s
500:	learn: 0.0469904	total: 2.71s	remaining: 2.7s
600:	learn: 0.0397926	total: 3.35s	remaining: 2.23s
700:	learn: 0.0338560	total: 3.91s	remaining: 1.67s
800:	learn: 0.0295784	total: 4.5s	remaining: 1.12s
900:	learn: 0.0253457	total: 4.97s	remaining: 546ms
999:	learn: 0.0220393	total: 6.16s	remaining: 0us
0:	learn: 0.3851127	total: 6.73ms	remaining: 6.72s
100:	learn: 0.1053903	total: 419ms	remaining: 3.73s
200:	learn: 0.0815476	total: 817ms	remaining: 3.25s
300:	learn: 0.0663069	total: 1.34s	remaining: 3.11s
400:	learn: 0.0548811	total: 1.89s	remaining: 2.82s
500:	learn: 0.0472019	total: 2.41s	remaining: 2.4s
600:	learn: 0.0398127	total: 2.92s	remaining: 1.94s
700:	learn: 0.0339372	total: 3.54s	remaining: 1.51s
800:	learn: 0.0285251	total: 4.25s	remaining: 1.05s
900:	learn: 0.0244552	total: 4.89s	remaining: 538ms
999:	learn: 0.0210805	total: 5.56s	remaining: 0us
R² Scores: [0.9127285  0.88077121 0.88538239 0.90143684 0.91685565]
Average R²: 0.899434917030128
0:	learn: 0.3783834	total: 8.32ms	remaining: 8.31s
100:	learn: 0.1052506	total: 680ms	remaining: 6.05s
200:	learn: 0.0805723	total: 1.31s	remaining: 5.21s
300:	learn: 0.0651217	total: 1.89s	remaining: 4.39s
400:	learn: 0.0549365	total: 2.52s	remaining: 3.76s
500:	learn: 0.0452304	total: 3.1s	remaining: 3.09s
600:	learn: 0.0390091	total: 3.75s	remaining: 2.49s
700:	learn: 0.0333101	total: 4.31s	remaining: 1.84s
800:	learn: 0.0284925	total: 4.74s	remaining: 1.18s
900:	learn: 0.0243937	total: 5.14s	remaining: 564ms
999:	learn: 0.0208649	total: 5.55s	remaining: 0us
0:	learn: 0.3794969	total: 5.11ms	remaining: 5.1s
100:	learn: 0.1018032	total: 972ms	remaining: 8.65s
200:	learn: 0.0800223	total: 2.4s	remaining: 9.54s
300:	learn: 0.0665577	total: 3.66s	remaining: 8.49s
400:	learn: 0.0554048	total: 4.79s	remaining: 7.15s
500:	learn: 0.0459659	total: 5.97s	remaining: 5.94s
600:	learn: 0.0385716	total: 6.79s	remaining: 4.51s
700:	learn: 0.0331637	total: 7.74s	remaining: 3.3s
800:	learn: 0.0288285	total: 8.19s	remaining: 2.04s
900:	learn: 0.0250925	total: 8.68s	remaining: 954ms
999:	learn: 0.0217112	total: 9.1s	remaining: 0us
0:	learn: 0.3654771	total: 13.7ms	remaining: 13.6s
100:	learn: 0.1009831	total: 606ms	remaining: 5.4s
200:	learn: 0.0813126	total: 1.04s	remaining: 4.14s
300:	learn: 0.0672490	total: 1.46s	remaining: 3.38s
400:	learn: 0.0558627	total: 1.95s	remaining: 2.92s
500:	learn: 0.0462434	total: 2.61s	remaining: 2.6s
600:	learn: 0.0390710	total: 3.05s	remaining: 2.02s
700:	learn: 0.0329016	total: 3.47s	remaining: 1.48s
800:	learn: 0.0279519	total: 4.69s	remaining: 1.17s
900:	learn: 0.0240839	total: 5.79s	remaining: 636ms
999:	learn: 0.0210700	total: 6.89s	remaining: 0us
0:	learn: 0.3796258	total: 13.6ms	remaining: 13.6s
100:	learn: 0.1051636	total: 1.18s	remaining: 10.5s
200:	learn: 0.0831720	total: 2.34s	remaining: 9.29s
300:	learn: 0.0679759	total: 3.51s	remaining: 8.14s
400:	learn: 0.0558960	total: 4.64s	remaining: 6.94s
500:	learn: 0.0469904	total: 5.73s	remaining: 5.71s
600:	learn: 0.0397926	total: 6.84s	remaining: 4.54s
700:	learn: 0.0338560	total: 7.93s	remaining: 3.38s
800:	learn: 0.0295784	total: 9.02s	remaining: 2.24s
900:	learn: 0.0253457	total: 10.1s	remaining: 1.11s
999:	learn: 0.0220393	total: 11.3s	remaining: 0us
0:	learn: 0.3851127	total: 9.11ms	remaining: 9.11s
100:	learn: 0.1053903	total: 848ms	remaining: 7.54s
200:	learn: 0.0815476	total: 1.31s	remaining: 5.21s
300:	learn: 0.0663069	total: 1.76s	remaining: 4.08s
400:	learn: 0.0548811	total: 2.18s	remaining: 3.26s
500:	learn: 0.0472019	total: 2.67s	remaining: 2.66s
600:	learn: 0.0398127	total: 3.32s	remaining: 2.2s
700:	learn: 0.0339372	total: 3.79s	remaining: 1.61s
800:	learn: 0.0285251	total: 4.33s	remaining: 1.08s
900:	learn: 0.0244552	total: 4.84s	remaining: 532ms
999:	learn: 0.0210805	total: 5.46s	remaining: 0us
Average RMSE: 0.12327515644670473

In [48]:
importance = pd.Series(
    cat_model.feature_importances_,
    index=new_train.columns
)

print(importance.sort_values(ascending=False).head(30))

remainder__TotalSF         15.363812
remainder__TotalHouseSF     8.132423
remainder__OverallScore     7.385775
remainder__OverallQual      6.111354
remainder__LotArea          3.986373
remainder__YearBuilt        3.533864
remainder__Fireplaces       3.308313
remainder__GrLivArea        3.182026
tf2__KitchenQual            2.984080
remainder__RemodelAge       2.980800
remainder__TotalBath        2.803276
remainder__GarageScore      2.729941
tf2__ExterQual              2.338081
remainder__BsmtFinSF1       1.746276
tf2__BsmtQual               1.481770
remainder__GarageArea       1.385033
remainder__GarageYrBlt      1.318045
tf2__GarageFinish           1.203878
remainder__GarageCars       1.124025
tf3__Foundation_PConc       1.063562
tf2__FireplaceQu            0.957213
remainder__HouseAge         0.953008
tf2__BsmtFinType1           0.920131
remainder__TotalBsmtSF      0.910078
remainder__1stFlrSF         0.813728
tf1__CentralAir_1           0.803987
remainder__BsmtUnfSF        0.775661
remainder__MoSold           0.725024
remainder__OverallCond      0.724854
remainder__LotFrontage      0.715770
dtype: float64

In [49]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    "depth": [4, 5, 6, 7, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "iterations": [300, 500, 800, 1000],
    "l2_leaf_reg": [1, 3, 5, 7, 9],
    "bagging_temperature": [0, 1, 3, 5],
    "random_strength": [1, 2, 5, 10]
}

cat = CatBoostRegressor(
    loss_function="RMSE",
    random_seed=42,
    verbose=0
)

search = RandomizedSearchCV(
    estimator=cat,
    param_distributions=param_grid,
    n_iter=50,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    random_state=42,
    verbose=2
)

search.fit(new_train, y_train)

print("Best Score:", search.best_score_)
print("Best Parameters:")
print(search.best_params_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
Best Score: 0.9040121926175161
Best Parameters:
{'random_strength': 1, 'learning_rate': 0.03, 'l2_leaf_reg': 1, 'iterations': 1000, 'depth': 4, 'bagging_temperature': 3}